# Generated by Django 4.2.5 on 2026-06-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='اسم الصيدلية')),
                ('owner_name', models.CharField(blank=True, max_length=120, verbose_name='اسم المالك')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='الهاتف')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='العنوان')),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name='الرقم الضريبي')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/', verbose_name='الشعار')),
                ('currency', models.CharField(default='ج.م', max_length=10, verbose_name='العملة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'بيانات الصيدلية',
                'verbose_name_plural': 'بيانات الصيدلية',
            },
        ),
    ]
