# Generated by Django 4.2.5 on 2026-06-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeLabelSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_width_mm', models.PositiveIntegerField(default=50, verbose_name='عرض الليبل (مم)')),
                ('label_height_mm', models.PositiveIntegerField(default=30, verbose_name='ارتفاع الليبل (مم)')),
                ('show_product_name', models.BooleanField(default=True, verbose_name='إظهار اسم الدواء')),
                ('show_sku', models.BooleanField(default=True, verbose_name='إظهار كود الصنف')),
                ('show_price', models.BooleanField(default=True, verbose_name='إظهار السعر')),
                ('show_company', models.BooleanField(default=False, verbose_name='إظهار الشركة')),
                ('font_size', models.PositiveIntegerField(default=10, verbose_name='حجم الخط')),
                ('barcode_height', models.PositiveIntegerField(default=40, verbose_name='ارتفاع الباركود')),
                ('copies_default', models.PositiveIntegerField(default=1, verbose_name='عدد النسخ الافتراضي')),
            ],
            options={
                'verbose_name': 'إعدادات ليبل الباركود',
                'verbose_name_plural': 'إعدادات ليبل الباركود',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود الفرع')),
                ('name', models.CharField(max_length=120, verbose_name='اسم الفرع')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='العنوان')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='الهاتف')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'فرع',
                'verbose_name_plural': 'الفروع',
                'ordering': ['code'],
            },
        ),
    ]
