# Generated by Django 4.2.5 on 2026-06-25 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_barcodelabelsettings_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiptSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_text', models.TextField(blank=True, default='شكراً لزيارتكم', verbose_name='نص الهيدر')),
                ('footer_text', models.TextField(blank=True, default='بالشفاء العاجل', verbose_name='نص الفوتر')),
                ('receipt_logo', models.ImageField(blank=True, null=True, upload_to='receipts/', verbose_name='لوجو الإيصال')),
                ('use_pharmacy_logo', models.BooleanField(default=True, verbose_name='استخدام شعار الصيدلية')),
                ('show_logo', models.BooleanField(default=True, verbose_name='إظهار اللوجو')),
                ('paper_width_mm', models.PositiveIntegerField(default=80, verbose_name='عرض الورق (مم)')),
                ('title_font_size', models.PositiveIntegerField(default=15, verbose_name='حجم خط العنوان')),
                ('body_font_size', models.PositiveIntegerField(default=12, verbose_name='حجم خط المحتوى')),
                ('show_cashier', models.BooleanField(default=True, verbose_name='إظهار الكاشير')),
                ('show_customer', models.BooleanField(default=True, verbose_name='إظهار بيانات العميل')),
                ('show_discount', models.BooleanField(default=True, verbose_name='إظهار الخصم')),
                ('auto_print', models.BooleanField(default=False, verbose_name='طباعة تلقائية بعد الترحيل')),
            ],
            options={
                'verbose_name': 'إعدادات إيصال البيع',
                'verbose_name_plural': 'إعدادات إيصال البيع',
            },
        ),
    ]
