DEFAULT_DASHBOARD_SHORTCUTS = [
    'product_add',
    'purchase_add',
    'sales_add',
    'return_add',
]

DASHBOARD_SHORTCUTS = [
    {
        'key': 'product_add',
        'label': 'إضافة منتج جديد',
        'icon': 'fa-plus',
        'icon_class': 'icon-blue',
        'url_name': 'product_add',
        'module': 'products',
        'perm': 'add',
    },
    {
        'key': 'purchase_add',
        'label': 'فاتورة مشتريات',
        'icon': 'fa-cart-plus',
        'icon_class': 'icon-green',
        'url_name': 'purchase_add',
        'module': 'purchases',
        'perm': 'add',
    },
    {
        'key': 'sales_add',
        'label': 'فاتورة مبيعات',
        'icon': 'fa-receipt',
        'icon_class': 'icon-purple',
        'url_name': 'sales_add',
        'module': 'sales',
        'perm': 'add',
    },
    {
        'key': 'return_add',
        'label': 'مرتجع فاتورة',
        'icon': 'fa-undo',
        'icon_class': 'icon-orange',
        'url_name': 'return_add',
        'module': 'sales',
        'perm': 'add',
    },
    {
        'key': 'stock_report',
        'label': 'استعلام مخزون',
        'icon': 'fa-search',
        'icon_class': 'icon-blue',
        'url_name': 'stock_report',
        'module': 'stock',
        'perm': 'view',
    },
    {
        'key': 'warranty_report',
        'label': 'تقرير الضمان',
        'icon': 'fa-shield-alt',
        'icon_class': 'icon-red',
        'url_name': 'warranty_report',
        'module': 'stock',
        'perm': 'view',
    },
    {
        'key': 'customer_payment',
        'label': 'تحصيل عميل',
        'icon': 'fa-hand-holding-usd',
        'icon_class': 'icon-green',
        'url_name': 'customer_payment',
        'module': 'customers',
        'perm': 'add',
    },
    {
        'key': 'supplier_payment',
        'label': 'سداد مورد',
        'icon': 'fa-money-bill-wave',
        'icon_class': 'icon-orange',
        'url_name': 'supplier_payment',
        'module': 'suppliers',
        'perm': 'add',
    },
    {
        'key': 'cash_ledger',
        'label': 'كشف الخزنة النقدية',
        'icon': 'fa-cash-register',
        'icon_class': 'icon-green',
        'url_name': 'cash_ledger',
        'module': 'expenses',
        'perm': 'view',
    },
    {
        'key': 'daily_report',
        'label': 'تقرير يومي',
        'icon': 'fa-calendar-day',
        'icon_class': 'icon-blue',
        'url_name': 'daily_report',
        'module': 'daily_report',
        'perm': 'view',
    },
    {
        'key': 'activity_log',
        'label': 'سجل الحركات',
        'icon': 'fa-history',
        'icon_class': 'icon-orange',
        'url_name': 'activity_log',
        'module': 'activity_log',
        'perm': 'view',
    },
    {
        'key': 'sales_profit_report',
        'label': 'تقرير الأرباح',
        'icon': 'fa-chart-line',
        'icon_class': 'icon-purple',
        'url_name': 'sales_profit_report',
        'module': 'sales',
        'perm': 'view',
    },
]

SHORTCUTS_BY_KEY = {item['key']: item for item in DASHBOARD_SHORTCUTS}
