# Generated by Django 4.2.5 on 2026-06-27 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacy', '0003_receipt_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, verbose_name='المستخدم')),
                ('action', models.CharField(choices=[('login', 'تسجيل دخول'), ('logout', 'تسجيل خروج'), ('create', 'إضافة'), ('update', 'تعديل'), ('delete', 'حذف'), ('post', 'ترحيل'), ('export', 'تصدير')], max_length=20, verbose_name='العملية')),
                ('section', models.CharField(blank=True, max_length=80, verbose_name='القسم')),
                ('description', models.TextField(blank=True, verbose_name='التفاصيل')),
                ('object_ref', models.CharField(blank=True, max_length=120, verbose_name='المرجع')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='الوقت')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to='pharmacy.branch')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سجل حركة',
                'verbose_name_plural': 'سجل الحركات',
                'ordering': ['-created_at'],
            },
        ),
    ]
